import Head from 'next/head'
import { useState } from 'react'
import Navbar from '../components/Bars/Navbar'
import Sidebar from '../components/Bars/Sidebars'
import StatisticsCard from '../components/Cards/StatisticsCard'
import CardBarChart from '../components/Chart/Chart'
import AddingFrom from '../components/Forms/AddingFrom'
import StudentEnroll from '../components/Forms/StudentEnroll'

export default function Home() {
  const [showSidebar, setShowSidebar] = useState(true)
  return (
    <div >
      <Head>
        <title>School Management Dashboard Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='home-container '>
        <Sidebar show={showSidebar} setShow={setShowSidebar} />
        <section className='container-right pb-10'>
          <Navbar show={showSidebar} setShow={setShowSidebar} />
          <div className={`${!showSidebar && "h-[100px]"}`}></div>
          <div className='flex light-bg justify-between items-center px-5 py-3'>
            <h2 className='text-xl font-bold text-primary'>School</h2>
            <div className="text-sm breadcrumbs">
              <ul>
                <li><a>Home</a></li>
                <li><a>Documents</a></li>
              </ul>
            </div>
          </div>

          {/* Top End Here  */}
          <div className='main-content-container lg:grid grid-cols-12  mt-10 gap-10 w-full lg:p-5'
          >
            {/* Start Left Side Of GRid  */}
            {/* Start Left Side Of GRid  */}

            <div className='lg:col-span-5 col-span-12 p-3'>
              <div className='grid lg:grid-cols-2 md:grid-cols-2 gap-5'>
                <StatisticsCard
                  color={'bg-[#71D875]'}
                  tColor="text-[#71D875]"
                  data={{ number: 2555, name: 'Students' }}
                  icon="fa-users"
                />

                <StatisticsCard
                  color={'bg-[#FF8423]'}
                  tColor="text-[#FF8423]"
                  data={{ number: 50, name: 'Teacher' }}
                  icon="fa-users"
                />
                <StatisticsCard
                  color={'bg-[#00AFF0]'}
                  tColor="text-[#00AFF0]"
                  data={{ number: 812, name: 'Attendance' }}
                  icon="fa-clipboard-user"
                />
                <StatisticsCard
                  color={'bg-[#FFC107]'}
                  tColor="text-[#FFC107]"
                  data={{ number: 44, name: 'Course' }}
                  icon="fa-graduation-cap"
                />
                <StatisticsCard
                  color={'bg-[#FF5274]'}
                  tColor="text-[#FF5274]"
                  data={{ number: '$1634', name: 'Expenses' }}
                  icon="fa-money-bill"
                />
                <StatisticsCard
                  color={'bg-[#D57FF8]'}
                  tColor="text-[#D57FF8]"
                  data={{ number: '$6634', name: 'Income' }}
                  icon="fa-money-bill"
                />
              </div>
              {/* End Statistics  */}
              {/* End Statistics  */}
              {/* Instractor Adding From  */}
              <AddingFrom />
              {/* Instractor Adding From  */}

              <div className='shadow p-4 mt-10 bg-white rounded-lg'>
                <h1 className='text-xl font-bold text-gray-600'>Active Classes</h1>
                <div className='flex justify-between py-5 mt-5 px-3 shadow'>
                  <h2 className='text-sp'>Astronomy 101</h2>
                  <i className="fa-solid icon fa-circle-plus"></i>
                </div>
                <div className='flex justify-between py-4 mt-2 px-3 shadow'>
                  <h2 className='text-sp'>Chemistry</h2>
                  <i className="fa-solid icon fa-circle-plus"></i>
                </div>
                <div className='flex justify-between py-4 mt-2 px-3 shadow'>
                  <h2 className='text-sp'>Biology</h2>
                  <i className="fa-solid icon fa-circle-plus"></i>
                </div>
                <div className='flex justify-between py-4 mt-2 px-3 shadow'>
                  <h2 className='text-sp'>Physics</h2>
                  <i className="fa-solid icon fa-circle-plus"></i>
                </div>
              </div>
            </div>

            {/* LEst Side End Here  */}
            <div className='lg:col-span-7 col-span-12 p-3'>
              <CardBarChart />
              <StudentEnroll />
            </div>
          </div>
          {/* Class Activities  */}

          <div className='p-5 bg-white'>
            <div className="overflow-x-auto">
              <table className="table table-zebra w-full">
                {/* <!-- head --> */}
                <thead className='bg-white'>
                  <tr >
                    <th>No</th>
                    <th>Name</th>
                    <th>Assigned professor</th>
                    <th>Date of Admit</th>
                    <th>Fees</th>
                    <th>Branch</th>
                  </tr>
                </thead>
                <tbody>
                  {
                    studentList.map(list => (
                      <tr key={list.id} className="shadow-xl mb-10">
                        <th>{list.id}</th>
                        <td>{list.name}</td>
                        <td>{list.propessor}</td>
                        <td>{list.propessor}</td>
                        <td>
                          {
                            list.fees
                              ?
                              <button
                                className='btn text-white btn-sm btn-success'>Paid</button>
                              :
                              <button className='btn
                               btn-sm btn-warning '>Paid</button>
                          }
                        </td>
                        <td>{list.branch}</td>
                      </tr>
                    ))
                  }
                </tbody>
              </table>
            </div>
          </div>
        </section>
      </main>

    </div>
  )
}

const studentList = [
  {
    id: 1,
    name: 'Fleece Marigold',
    propessor: 'Indigo Violet',
    date: '02/06/2021',
    fees: true,
    branch: 'Science'
  },
  {
    id: 2,
    name: 'Theodore handle',
    propessor: 'Niles Peppertrout',
    date: '03/05/2021',
    fees: false,
    branch: 'Commarce'
  },
  {
    id: 3,
    name: 'Archhibald Nortbottom Marigold',
    propessor: 'Jeckson Pot',
    date: '05/03/2022',
    fees: true,
    branch: 'Arts'
  },
  {
    id: 4,
    name: 'Archhibald Nortbottom Marigold',
    propessor: 'Jeckson Pot',
    date: '05/03/2022',
    fees: true,
    branch: 'Arts'
  },
  {
    id: 5,
    name: 'Archhibald Nortbottom Marigold',
    propessor: 'Jeckson Pot',
    date: '05/03/2022',
    fees: true,
    branch: 'Arts'
  }
]