name: Publish Website to Cpanel
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.0.0
        with:
         ftp-server: 'ftp.sifulcrypto.com'
          ftp-username: 'codehouse@codehouse.mdtamiz.xyz'
          ftp-password: '@tomiz.com'
          branch: master
          cpanel_token: 'GT70W0YOQ8Y9K7X6PS1YTWF3V2IEAYHF'