on:
  push:
    branches:
    - master

jobs:
 FTP-Deploy-Action:
    runs-on: ubuntu-latest
    name: FTP-Deploy-Action
    steps:
      - uses: action/checkout@2.1.0
      with:
      fetch-depth: 2
    - name : FTP-Deploy-Action
      uses: pinkasey/cpanel-deploy-action@v1.0.0user
     with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USENAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          branch: master