name: Publish Website to Cpanel
on:
  push:
    branches:
    - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        uses: actions/checkout@v2
    - name : Sync files
      user: Samkirkland/FTP-Deploy-action@4.3.0
      with:
          server: 'ftp.sifulcrypto.com'
          username: 'codehouse@codehouse.mdtamiz.xyz'
          password: '@tomiz.com'
          server-dir: /other-websites/codehouse/