name: Publish Website to Cpanel
on:
  push:
    branches:
    - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        uses: actions/checkout@v2
    - name : Sync files
      with:
          server: 'ftp.sifulcrypto.com'
          username: 'codehouse@codehouse.mdtamiz.xyz'
          password: '@tomiz.com'
          cpanel_token: 'GT70W0YOQ8Y9K7X6PS1YTWF3V2IEAYHF'